src/components/pages/DataAnalytics.js

Set initDate.absolute and initDate.delta to null after first start of tracardi

Fix: Null date on first start of Tracardi

---

src/components/elements/charts/BarChart.js
src/components/elements/charts/LineChart.js
src/components/elements/datepickers/CalendarPicker.js
src/components/elements/datepickers/DateTimePicker.js
src/components/elements/datepickers/NowDateTime.js
src/components/elements/datepickers/RelativePicker.js
src/components/elements/details/CredentialsDetails.js
src/components/elements/details/DetailHeader.js
src/components/elements/details/DetailKeyValue.js
src/components/elements/details/DetailProperties.js
src/components/elements/details/EventDetails.js
src/components/elements/details/FlowDetails.js
src/components/elements/details/ProfileDetails.js
src/components/elements/details/RuleDetails.js
src/components/elements/details/RuleStats.js
src/components/elements/details/SegmentDetails.js
src/components/elements/details/SourceDetails.js
src/components/elements/details/UqlDetails.js

Resubmitting same changes as last PR, should be much more manageable now! :)

Add proptypes

---

src/components/elements/forms/CopyTraitsForm.css
src/components/elements/forms/CopyTraitsForm.js

Functioning per wireframe, calls an external onChange and passes current value object. Let me know if you'd like more styling like transitions or anything else. Thanks!

added copy trait form

---

src/components/authentication/SignIn.js

Display information on conflict between GUI and API on Login form #63
Display information on conflict between GUI and API above login form
----

Conflict API and GUI verision

---

src/components/authentication/SignIn.js

Please DO NOT DELETE this template. Fill it. PR without this template will be discarded. We need your declaration that
your contribution is MIT licensed without it, we can not merge your code.
I hereby declare this contribution to be licenced under the MIT license
PRs without ticked MIT license will bot be accepted - Sorry.
---
Add Tracardi API endpoint to Login Form #59
---
**Please** following this checklist to help us incorporate your contribution quickly and easily:

Remote API endpoint dropdown

---

package.json
src/components/elements/forms/ConsentTypeForm.js
src/components/elements/lists/ConsentTypeList.css
src/components/elements/lists/ConsentTypeList.js
src/components/pages/TryOut.js
yarn.lock

Consent type form and list (#62) 
Added a form that adds Consent Types and a list using react-window to display and delete them. The search limit and starting index is controlled by the user. 
----

Consent type form and list #62

---

src/components/pages/ProfileManagement.js

Create Page for user management #259
Page for profile management with froms : username, password, email, fullName, disabled, role
----

create page for profile management

---

src/components/elements/forms/ScheduledForm.js
src/components/elements/forms/inputs/TimeInput.js
src/components/pages/TryOut.js

* Test your code throughly before PR.
Form: New form for adding scheduled events #31
New form for adding scheduled event with modified timeinput for this purpose.
----

Form scheduled events

---

src/components/elements/lists/JsObjectList.js

Remove fetchData #286
Removed fetchData
----

refactoring fetchData to asyncRemote

---

src/components/AppBox.js
src/components/pages/Users.js

User site (#240, #74)
created user management site
----

User site (#240, #74)

---

src/components/elements/details/DestinationDetails.js

destination detail button icons
added proper icons to destination detail buttons
----

destination detail button icons

---

src/components/elements/forms/EditUserForm.js
src/components/pages/EventTags.js

Endpoint renaming (#406)
renamed endpoints
----

endpoint renaming (#406)

---

src/components/AppBox.js
src/components/menu/MainMenu.js
src/components/pages/UserSelfInspect.js

user self-edit site
added the page where user can change their account's properties
----

user self-edit site

---

src/components/AppBox.js
src/components/elements/forms/EditAccountForm.js
src/components/menu/MainMenu.js
src/components/pages/UserAccount.js
src/components/pages/UserSelfInspect.js

account page refactoring
refactored account page changes
----

account page refactoring

---

src/components/elements/IconSelector.js
src/components/elements/forms/PluginForm.css
src/components/elements/forms/PluginForm.js

new plugin details form (#102)
added new plugin details form
----

new plugin details form (#102)

---

src/components/pages/Settings.js

es and redis check buttons (#415)
Added new buttons in settings tab
----

es and redis check buttons (#415)

---

src/components/pages/Logs.js
src/components/pages/UserLogs.js

logs filtering (#422)
added functional filter text field on logs page
----

logs filtering (#422)

---

src/components/elements/details/EventSourceDetails.js
src/components/elements/forms/PluginForm.js
src/components/pages/Dashboard.js

PR Title format: 
event source traffic details (#424)
**Please** add a meaningful description for your change here
----added new tab in event source details for this purpose

event source traffic details (#424)

---

src/components/elements/sliders/SessionSlider.js

Session slider error handling
Added error handling to session slider component
----

Session slider error handling

---

src/components/flow/FlowNodeIcons.js

civicrm icon (#436)
added icon for civicrm related content
----

civicrm icon (#436)

---

src/components/elements/forms/JsonForm.js
src/components/elements/forms/JsonFormComponents.js
src/components/elements/forms/KeyValueForm.js
src/components/elements/forms/NodeInitForm.js
src/components/elements/forms/TracardiProServiceConfigForm.js
src/components/pages/TryOut.js
src/misc/recursiveObjectMerge.js

keyValueList bug fix (#121)
fixed bug with the component not deleting values
----

keyValueList bug fix (#121)

---

src/components/elements/forms/KeyValueForm.js
src/components/flow/FlowNodeIcons.js
src/components/pages/TryOut.js

Key value component select feature
added discussed feature
----

Key value component select feature

---

src/components/elements/details/CompactEventDetails.css
src/components/elements/details/CompactEventDetails.js
src/components/elements/details/ProfileSessionsDetails.js
src/components/elements/sliders/SessionSlider.js
src/components/elements/steppers/SessionStepper.js
src/components/pages/TryOut.js

Compact event details & profile sessions details
added two components mentioned in title
----

Compact event details & profile sessions details

---

src/components/elements/forms/EventSourceForm.js

returns_profile option implementation
----

returns_profile option implementation

---

src/components/elements/forms/ResourceForm.js

consent requirement field removed (#127)
----

consent requirement field removed (#127)

---

src/components/elements/steppers/SessionStepper.js

dollar sign bug fix (#129)
----

dollar sign bug fix (#129)

---

src/components/AppBox.js
src/components/pages/ElasticClusterHealthInfo.js

cluster health site (#464)
----

cluster health site (#464)

---

src/components/AppBox.js
src/components/pages/ElasticClusterHealthInfo.js
src/components/pages/ElasticIndicesInfo.js

elastic indices details (#97)
----

elastic indices details (#97)

---

src/components/pages/UserAccount.js

logout fix 

---

src/components/elements/details/PropertyField.js

profile boolean trait fix (#482)
----

profile boolean trait fix (#482)

---

src/components/elements/forms/JsonForm.js
src/components/elements/forms/JsonFormComponents.js
src/components/elements/forms/NodeInitForm.js
src/components/elements/forms/inputs/DotAccessor.js
src/components/flow/NodeDetails.js
src/effects/AfterMountEffect.js
src/index.css

Form validation error (#140)
JSON Form does not validate
----
- [x ] I hereby declare this contribution to be licenced under the [MIT license](https://opensource.org/licenses/MIT)

140 validation does not work on the wf node

---

src/components/elements/forms/AutoComplete.js
src/components/elements/forms/ImportForm.js
src/components/elements/forms/JsonForm.js
src/components/elements/forms/JsonFormComponents.js
src/components/elements/tui/TuiApiUrlInput.js
src/components/flow/editors/ConfigEditor.js

Resource dropdown on json form does not show error message (#143)

143 resource dropdown on json form does not show error message

---

src/misc/converters.js

dashboard NaN bug fix (tracardi-gui #142)
fixed bug from the issue
----

dashboard NaN bug fix (tracardi-gui #142)

---

src/components/elements/forms/pro/TracardiProSignUpForm.js

Sing-up typo fix (#155)

---

src/components/elements/tui/TuiForm.js
src/components/pages/TryOut.js

Tui form reload bug fix (#110)
fixed
----

Tui form reload bug fix (#110)

---

src/components/elements/charts/EventsTimeLine.js

dashboard timezone fix (#458)
Now Dashboard timeline takes timezone into account
----

dashboard timezone fix (#458)

---

src/components/authentication/Logout.js
src/components/authentication/SignIn.js
src/remote_api/entrypoint.js

API URL from params on login page (#507)
API URL can be passed by api_url query parameter in URL
----

API URL from params on login page (#507)

---

src/components/menu/MainMenu.js

hiding menu items (#507)

---

src/components/App.js
src/components/AppBox.js
src/components/elements/forms/NewUserForm.js
src/components/elements/lists/cards/AdvancedSquareCard.css
src/components/pages/UserAccount.js
src/components/pages/Users.js

data admin role implementation (#490)
----

data admin role implementation (#490)

---

src/components/pages/ElasticIndicesInfo.js

button for deleting indices (#138)
added button for deleting index in indices inspect section of GUI
----

button for deleting indices (#138)

---

src/components/flow/FlowNode.css
src/components/flow/StartNode.js

Start node fixes (#161, #162)
----

Start node fixes (#161, #162)

---

src/components/flow/FlowEditorPane.js

flow centering bug fix (#528)
----

flow centering bug fix (#528)

---

src/components/elements/details/FlowDetails.js
src/components/elements/forms/FlowForm.js
src/components/elements/lists/cards/AdvancedSquareCard.js
src/components/flow/FlowEditor.js
src/components/flow/FlowEditorOps.js
src/components/flow/FlowEditorPane.js
src/components/pages/Flows.js

Flow enabled regression (#527)
----

Flow enabled regression (#527)

---

src/components/ApiUrlSelector.js
src/components/authentication/SignIn.js

moved api url reading to ApiUrlSelector, added validation (#158)
----

moved api url reading to ApiUrlSelector, added validation (#158)

---

src/components/elements/forms/ImportForm.js
src/components/elements/tui/TuiSelectEventSource.js

Custom event source for import (#459)
now it's possible to add custom event source in import configuration form
----

Custom event source for import (#459)

---

src/components/ApiUrlSelector.js

API URL validation (#166)
----

API URL validation (#166)

---

src/components/elements/forms/inputs/FilterTextField.js
src/components/flow/EdgeDetails.js
src/components/flow/FlowEditorPane.js
src/components/flow/edges/BoldEdge.js
src/components/flow/edges/CancelEdge.js
src/components/flow/edges/InfoEdge.js
src/components/flow/edges/StopEdge.js

Edge Details and handling of display of details drawer.
Pull request title (#172 )
Adds edge names on frontend. 
----

Edge Details and handling of display of details drawer.

---

src/components/ApiUrlSelector.js

error message fix (#171)

---

src/components/authentication/SignIn.js

removed unnecessary state (#170)
----

removed unnecessary state (#170)

---

src/components/AppBox.js
src/components/pages/Migrations.js

migration front-end (#181)
----

migration front-end (#181)

---

src/components/authentication/SignIn.js

quick bug fix
added mounted ref manipulation so progress state can update 
----

quick bug fix

---

src/components/pages/Migrations.js

tasks management for migration 
----

tasks management for migration 

---

src/components/elements/misc/BackgroundTaskProgress.js

progress calculating

---

src/components/elements/forms/ListOfDottedInputs.js

allow duplicates param on ListOfDottedInputs (#564)
----

allow duplicates param on ListOfDottedInputs (#564)

---

src/components/pages/Migrations.js

PR Title format: 
warning when re-doing migration for same version

added warning about redoing migration

---

src/components/elements/forms/EditUserForm.js
src/components/elements/forms/NewUserForm.js
src/components/pages/Users.js

user account expiration date (#523)
----

user account expiration date (#523)

---

src/components/elements/forms/AutoComplete.js
src/components/elements/forms/ImportForm.js
src/components/elements/tui/TuiSelectEventSource.js

event source selector 
fix tracardi#531
----

event source selector fix (#573)

---

src/components/elements/lists/AutoLoadList.js

auto load list bug fix

---

src/components/AppBox.js
src/components/menu/MainMenu.js

roles fixes (#595)

---

src/components/elements/lists/rows/RuleRow.css
src/components/elements/lists/rows/RuleRow.js
src/components/rules/FlowRules.js

rules deleting button (#182)

---

src/components/AppBox.js

admin permissions fix

---

src/components/elements/charts/EventsTimeLine.js
src/components/elements/metrics/MetricTimeLine.js
src/components/pages/Dashboard.js

now dashboard does scale (#196)

now dashboard does scale (#196)

---

src/components/elements/forms/JsonForm.js
src/components/elements/forms/JsonFormComponents.js

minor changes to autocomplete (#139)

Make JSON FORM field with available frields from event index (#139)

---

src/components/elements/forms/JsonForm.js
src/components/elements/forms/JsonFormComponents.js

contentInput now works fully properly (#615)

contentInput now works fully properly (#615)

---

src/components/elements/forms/ResourceForm.js
src/components/flow/actions/MdManual.js

resource documentation (#510)

---

src/components/AppBox.js
src/components/authentication/SignIn.js
src/components/elements/forms/Button.js
src/components/elements/forms/JsonForm.js
src/components/elements/forms/JsonFormComponents.js
src/components/elements/forms/ReportForm.js
src/components/elements/forms/inputs/ReportConfigInput.js
src/components/flow/FlowNodeIcons.js
src/components/flow/SidebarLeft.js
src/components/pages/Reports.js

Report module (#208)

---

src/components/ApiUrlSelector.js
src/components/authentication/SignIn.js

Can not change Tracardi API from login form (#647)

Can not change Tracardi API from login form (#647)

---

src/components/flow/FlowNode.js

Can not connect nodes when append payload is turned on (#666)
fixes #666
----

Can not connect nodes when append payload is turned on (#666)

---

src/components/elements/details/EventManagementDetails.js
src/components/elements/forms/EventManagementForm.js

event reshaping

---

.github/pull_request_template.md

Please DO NOT DELETE this template. Fill it. PR without your declaration that you licence your code under MIT will 
be discarded. 
Tips
* Test your code throughly before PR.
Pull request title (#<issue-id>)
----
To make clear that you license your contribution under the MIT you have to acknowledge this by …

misc spelling and cleanup fixes.

---

src/components/elements/forms/NodeInitForm.js

Can not edit number of repeates of retries in the plugin Runtime configuration[#207](https://github.com/Tracardi/tracardi-gui/issues/207)
fixes #207 
----

Can not edit number of repeates of retries in the plugin Runtime configuration #207

---

src/components/elements/forms/EventManagementForm.js

Event reshaping is not working properly[#678](https://github.com/Tracardi/tracardi/issues/678)

Event reshaping is not working properly #678

---

src/components/flow/SidebarLeft.css
src/components/flow/SidebarLeft.js

Add infor about more plugins.[#222](https://github.com/Tracardi/tracardi-gui/issues/222)
fixes #222 
----

Add infor about more plugins.#222

---

src/components/flow/FlowEditorPane.js

Feature: Copy/Duplicate things #695
added node copying feature
----

Feature: Copy/Duplicate things #695

---

README.md

Please DO NOT DELETE this template. Fill it. PR without your declaration that you licence your code under MIT will 
be discarded. 
Tips
Pull request title (#<issue-id>)
----
To make clear that you license your contribution under the MIT you have to acknowledge this by …

update docs to include redis requirement

---

src/components/flow/FlowNodeIcons.js

Adds SMS icon needed for SMS77 plugin.
Tips
Pull request title (#<issue-id>)
----
- [x ] I hereby declare this contribution to be licensed under …

Adds sms icon

---

src/components/elements/details/DetailProperties.js
src/components/elements/details/ResourceDetails.js
src/components/flow/FlowNodeIcons.js
src/index.css
src/misc/typeChecking.js

New resource details page

---

src/components/elements/datepickers/DaysPassed.js
src/components/elements/datepickers/TimeDifference.js

Please DO NOT DELETE this template. Fill it. PR without your declaration that you licence your code under MIT will 
be discarded. 
Tips
Pull request title (#235)
I Implemented a component that counts the days passed. Here is the preview of the component and the helper function:
I haven't tested out the component yet cause I have bad luck in setting up docker (WSL issue) but I am confident that the …

ISSUE #235 - feat: DaysPassed component that counts days passed from a given date 

---

src/components/elements/misc/DateValue.js
src/misc/formaters.js

Remove unused imports and variables, merge duplicate properties.
Please DO NOT DELETE this template. Fill it. PR without your declaration that you licence your code under MIT will 
be discarded. 
Tips
Fix simple compiler warnings
Remove unused imports and variables, merge duplicate properties.
----
We need your declaration that your contribution is MIT licensed without it, we can not merge your …

Fix simple compiler warnings

---

src/components/flow/FlowEditor.js
src/components/menu/MainMenu.css
src/components/menu/MainMenu.js
src/redux/reducers/appSlice.js
src/redux/store.js

use redux + useLocation(in react-router-dom) + useEffect realize left menu active style.
**This program may not be the best solution, this is just a simple attempt on my part, welcome to discuss.**

feat(menu): add active style for left menu

---

src/components/elements/charts/EventLineChart.js
src/components/elements/charts/EventsTimeLine.js
src/components/elements/charts/ProfileLineChart.js
src/components/elements/charts/SessionLineChart.js
src/components/elements/details/EventReshapingDetails.js
src/components/elements/details/EventValidationDetails.js
src/components/elements/details/LiveSegmentDetails.js
src/components/elements/details/SegmentDetails.js
src/components/elements/lists/_TracardiProRunningServicesList.js
src/components/elements/metrics/AvgEventTimeCounter.js
src/components/elements/metrics/EventCounter.js
src/components/elements/metrics/InstancesCounter.js
src/components/elements/metrics/ProfileCounter.js
src/components/elements/metrics/SessionCounter.js
src/components/pages/Dashboard.js

spelling error fix

---

src/components/authentication/SignIn.js

fix sigin page password input error

---

src/components/flow/FlowEditorPane.js

fix flow page anomalous sub-component re-render
